version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    container_name: fcxlabs_db_dev
    environment:
      POSTGRES_DB: "fcxlabs_db"
      POSTGRES_USER: "fcxlabs_db_dev"
      POSTGRES_PASSWORD: "Password"
      ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql@15/data:rw
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@fcxlabs.dev"
      PGADMIN_DEFAULT_PASSWORD: "Password"
    ports:
      - "16543:80"
    depends_on:
      - db
  api:
    build: ./api
    ports:
      - "5000:80"
    depends_on:
      - db
  web:
    build: ./web
    ports:
      - "80:3000"
    environment:
      - "API_URL=http://172.23.239.162:5000"
    depends_on:
      - api

volumes:
  postgresql_data:
